name: Run Tests + Upload Coverage

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2      # <--------- This part is very important (fetch-depth must be 2, or deeper)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: pcov
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs
      - name: Run tests
        run: ./vendor/bin/pest --coverage-clover=build/logs/clover.xml
      - name: Generate Type Coverage
        run: ./vendor/bin/pest --type-coverage --type-coverage-json=pest-type-coverage.json
      - name: Upload Coverage
        env:
          OTTERWISE_TOKEN: ${{ secrets.OTTERWISE_TOKEN }}
        run: bash <(curl -s https://raw.githubusercontent.com/getOtterWise/bash-uploader/main/uploader.sh)
